spring.application.name=Trading

server.port = 5454

# MySQL Datasource Configuration
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/trading_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

stripe.api.key =test

razorpay.api.key =test
razorpay.api.secret =test

#WallerController needs to be uncommented
#Have to make changes for Stripe api(Check for Razorpay api order in api testing section
#Make changes to razorpay and stripe api in applicatio propertties

